name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Lua (not LuaJIT)
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: 5.4
    - name: Setup LuaRocks
      uses: leafo/gh-actions-luarocks@v4
    - name: Install Busted
      run: luarocks install busted
    - name: Run Tests
      run: busted specs