name: Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup LuaJIT
        uses: leafo/gh-actions-lua@v10
      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Install dkjson
        run: luarocks install dkjson
      - name: Generate JSON
        run: lua scripts/generate-json.lua