name: Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Install Busted
        run: luarocks install busted
      - name: Run Tests
        run: busted specs
      - name: Install dkjson
        run: luarocks install dkjson
      - name: Generate JSON
        run: lua scripts/generate-json.lua
      - name: Upload JSON
        uses: actions/upload-artifact@v4
        with:
          name: json
          path: love-api.json
      - name: Release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
